# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: 一蓑烟雨的blog
email: 1114519278@qq.com
description: >- # this means to ignore newlines until "baseurl:"
  '欢迎来到一蓑烟雨的blog，这里记录了我的一些琐碎的问题及解答还有自己总结感悟的文章，欢迎大家留言或者邮箱讨论。'
baseurl: "" # the subpath of your site, e.g. /blog
url: "http(s)://spysyyrps.github.io" # the base hostname & protocol for your site, e.g. http://example.com
encodeing: 'utf-8'
defaults:
  -
    scope:
      path: ''
      type: 'post'
    value:
      layout: ''
      author: '一蓑烟雨'
      comments: true
      share: true
social:
  github: 'spysyyrps'
  codepen: ''
  rss: feed.xml
comment: true
remote_theme: "mmistakes/minimal-mistakes@4.24.0"
# Build settings
#theme: minima
plugins:
  - jekyll-feed
  - jekyll-include-cache

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
